export const SEO_SCORE = {
  BASE: 100,
  DEDUCTIONS: {
    STATUS_4XX_5XX: 50,
    MISSING_TITLE: 20,
    TITLE_TOO_LONG: 10,
    MISSING_META_DESC: 15,
    META_DESC_TOO_LONG: 5,
    MISSING_H1: 15,
    MULTIPLE_H1: 10,
    IMAGE_MISSING_ALT: 5,
    IMAGE_MISSING_ALT_MAX: 20,
    LOAD_TIME_SLOW: 10,
    LOAD_TIME_VERY_SLOW: 20,
  },
  THRESHOLDS: {
    TITLE_MAX_LENGTH: 60,
    META_DESC_MAX_LENGTH: 160,
    LOAD_TIME_SLOW_MS: 3000,
    LOAD_TIME_VERY_SLOW_MS: 5000,
  },
  CATEGORIES: {
    CRITICAL_BELOW: 50,
    WARNING_BELOW: 80,
  },
} as const;

export type IssueCategory = 'CRITICAL' | 'WARNING' | 'PASSED';
export type ScanStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
